import { INDICATOR_MODE_INDETERMINATE, INDICATOR_MODE_DETERMINATE, INDICATOR_MODE_DEFAULT } from "./modes.js";
import ProgressIndicator from "./indicator.js";

module.exports.INDICATOR_MODE_DEFAULT = INDICATOR_MODE_DEFAULT;
module.exports.INDICATOR_MODE_DETERMINATE = INDICATOR_MODE_DETERMINATE;
module.exports.INDICATOR_MODE_INDETERMINATE = INDICATOR_MODE_INDETERMINATE;

module.exports.ProgressIndicator = ProgressIndicator;
